-- =============================================================================
-- Migration: 002 — Create users Table
-- =============================================================================
-- Run order  : #2
-- Depends on : 001_enable_extensions_trigger.sql
-- Description: Creates the core authentication and identity table.
--              Stores credentials (bcrypt hash) and system access roles.
-- =============================================================================

-- Central authentication table for all system actors (customers, staff, admins).
-- Uses UUID primary keys generated by pgcrypto's gen_random_uuid().
CREATE TABLE IF NOT EXISTS users (
  id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name       VARCHAR(255)  NOT NULL,
  email           VARCHAR(255)  NOT NULL UNIQUE,
  -- Passwords are never stored in plaintext; holds bcrypt hash (12 salt rounds)
  password_hash   TEXT          NOT NULL,
  -- System role for RBAC authorization (extended to 7 roles in migration 010)
  role            VARCHAR(50)   NOT NULL DEFAULT 'customer'
                    CHECK (role IN ('admin', 'manager', 'employee', 'customer')),
  -- Soft-delete flag: inactive users are blocked from logging in without losing audit history
  is_active       BOOLEAN       NOT NULL DEFAULT TRUE,
  last_login_at   TIMESTAMPTZ,
  created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- Trigger to maintain updated_at timestamp on row mutation
CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Performance indexes for frequent lookups
CREATE INDEX IF NOT EXISTS idx_users_email     ON users(email);       -- Fast login authentication lookup
CREATE INDEX IF NOT EXISTS idx_users_role      ON users(role);        -- Filtering users by authorization role
CREATE INDEX IF NOT EXISTS idx_users_is_active ON users(is_active);   -- Filtering active accounts

COMMENT ON TABLE users IS 'System users — admins, managers, employees, and customers';

